name: Xcode - Build and Analyze

on:
  push:
    branches: [ "senpai" ]
  pull_request:
    branches: [ "senpai" ]

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-13

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Select Xcode 15.2
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - name: Build and Analyze
        run: |
          xcodebuild clean build analyze CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -scheme "USBNotifier" | xcpretty && exit ${PIPESTATUS[0]}
